spring.application.name=risk

server.port=8084

patient-service.base-url=http://localhost:8081
notes-service.base-url=http://localhost:8083

security.user.name=gateway
security.user.password=gateway-pwd